Books/urls.py
from django.urls import path
from Books.views import *

urlpatterns = [
   
    
]

Dashboard/urls.py
from django.urls import path
from Dashboard.views import *

app_name = "dashboard"

urlpatterns = [
    path('', CustomAdmin, name="CustomAdmin"),
    path('table/', custom_table, name="custom_table"),
    path('banner_section/',banner_section, name='banner_section'),
    path('banner_section/add_banner/', add_banner, name="add_banner"),
    path('banner_section/editdata/<int:id>/', editdata, name='editdata'),
    path('banner_delete/<int:id>/', banner_delete, name='banner_delete'),
    path('banner_section/on_sale/<int:id>/', on_sale_banner, name="on_sale_banner"),
    path('banner_section/edit_offer/<int:id>/', edit_offer_banner, name="edit_offer_banner"),
    path('books_category/', book_category_page, name="book_category_page"),
    path('book_category/edit/<int:id>/', edit_category, name="edit_category"),
    path('book_category/edit_category_delete/<int:id>/', book_category_delete, name="category_delete"),
    path('book_category/add_category/', add_book_category, name="add_book_category"),
    path('book_category/book_filter_category/<int:id>', product_by_category, name="product_by_category"),
    path('book_category/book_filter_author/<int:id>', product_by_author, name="product_by_author"),
    path('books/', all_books, name="all_books"),
    path('books/add_book/', add_book, name="add_book"),
    path('author/', author, name="author"),
    path('author/author_edit/<int:id>', author_edit, name="author_edit"),
    path('author/author_delete/<int:id>', author_delete, name="author_delete"),
    path('author/author_add/', author_add, name="author_add"),
    
    
]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from .views import admin_page
from django.conf import settings
from django.conf.urls.static import static
# from e_commerce import Dashboard


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('IndexPage.urls')),
    path('dashboard/',admin_page, name='admin_page'),
    path('dashboard/', include(('Dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('book/', include('Books.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Books/models.py
from django.db import models
from django_resized import ResizedImageField
from django_cleanup import cleanup
import os
from ckeditor.fields import RichTextField
import random
from datetime import date
# Create your models here.

def upload_image_path(instance, filename):
    extention = filename.split(".")[1]
    filename = f"{instance.name}-{instance.book_code}.{extention}"
    return os.path.join('books/', filename)
def author_image_path(instance, filename):
    extention = filename.split(".")[-1]
    filename = f"{instance.name}-{random.randint(100000, 999999)}.{extention}"
    return os.path.join('Author/', filename)


class Category(models.Model):
    name = models.CharField(max_length=250, blank=True, null=True)
    def __str__(self):
        return self.name if self.name else "No Name"
class Author(models.Model):
    name = models.CharField(max_length=250, blank=True, null=True)
    image = ResizedImageField(size=[500,300], quality=80,upload_to=author_image_path, null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    
    def __str__(self):
        return self.name if self.name else "No Name"
    
class Format(models.Model):
    format = models.CharField(max_length=250, blank=True, null=True)
    def __str__(self):
        return self.format if self.format else "No format"
@cleanup.select
class Book(models.Model):
    name = models.CharField(max_length=250, null=True, blank=True)
    book_code = models.CharField(max_length=250, null=True, blank=True)
    price = models.DecimalField( max_digits=10, decimal_places=2, default=0)
    discount_price = models.DecimalField( max_digits=10, decimal_places=2, default=0)
    image = ResizedImageField(size=[500,300], quality=80,upload_to=upload_image_path, null=True, blank=True)
    stock = models.PositiveIntegerField(default=0)
    short_details = RichTextField(null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)
    format = models.ForeignKey(Format, on_delete=models.PROTECT, blank=True, null=True)
    page = models.IntegerField(max_length=250, blank=True, null=True)
    publication_data = models.DateField(default=date.today)
    language = models.CharField(max_length=250, blank=True, null=True)
    
    def __str__(self):
        return self.name if self.name else "No Name"
    
    @property
    def in_stock(self):
        return self.stock > 0
    

Books/views.py
from django.shortcuts import render

# Create your views here.

Dashboard/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from banner.models import *
from Books.models import *
# Create your views here.
@login_required
def CustomAdmin(request):
    # context ={}
    return render(request, "html/dashboard/admin.html")

@login_required
def custom_table(request):
    return render(request, "html/dashboard/side-menu-light-post.html")

@login_required
def banner_section(request):
    context ={}
    banners = Banner.objects.all()
    on_offers = on_offer.objects.first()
    sale_offers = sale_offer.objects.first()
    context['banners'] = banners
    context['on_offers'] = on_offers
    context['sale_offers'] = sale_offers
    return render(request, 'html/dashboard/admin.html', context)

@login_required
def add_banner(request):
    if request.method == "POST":
        title = request.POST.get('title')
        is_active =True if request.POST.get('is_active') else False
        description = request.POST.get('description')
        image = request.FILES.get('image')
        banner = Banner(title=title, is_active=is_active, description=description, image=image)
        banner.save()
        messages.success(request, "Banner Add Successfully")
        return redirect('dashboard:banner_section')
    return render(request, "html/dashboard/add_banner.html")

@login_required
def editdata(request, id):
    banner = get_object_or_404(Banner, id=id)
    if request.method == "POST":
        banner.title = request.POST.get('title')
        banner.description = request.POST.get('description')
        banner.is_active = True if request.POST.get('is_active') == 'on' else False

        if request.FILES.get('image'):
            banner.image = request.FILES.get('image')
        banner.save()
        messages.success(request, "Banner Updated Successfully")
        return redirect('dashboard:banner_section')
    context = {
        'banner': banner
    }
    return render(request, 'html/dashboard/side-menu-light-post.html', context)

@login_required
def banner_delete(request, id):
    banner = get_object_or_404(Banner, id=id)
    banner.delete()
    messages.success(request, "Banner Delete Successfully")
    return redirect('dashboard:banner_section')

@login_required
def on_sale_banner(request):
    return render(request, 'html/dashboard/on_sale.html')

@login_required
def on_sale_banner(request, id):
    on_sale = get_object_or_404(sale_offer, id=id)
    if request.method == "POST":
        on_sale.title = request.POST.get('title')
        on_sale.discount = request.POST.get('discount')
        on_sale.save()
        messages.success(request, "Updated Successfully")
        return redirect('dashboard:banner_section')

    context={}
    context['on_offer'] = on_sale
    return render(request, 'html/dashboard/on_sale.html', context)

@login_required
def edit_offer_banner(request, id):
    edit_offer = get_object_or_404(on_offer, id=id)
    if request.method == "POST":
        edit_offer.title = request.POST.get('title')
        edit_offer.discount = request.POST.get('discount')
        edit_offer.save()
        messages.success(request, "Updated Successfully")
        return redirect('dashboard:banner_section')
    context={}
    context['edit_offer'] = edit_offer
    return render(request, 'html/dashboard/edit_offer.html', context)

def all_books(request):
    context = {}
    book = Book.objects.all()
    context['books'] = book
    return render(request, 'html/dashboard/Books.html', context)

def add_book(request):
    context={}
    authors = Author.objects.all()
    categorys = Category.objects.all()
    all_formats = Format.objects.all()
    context['formats'] = all_formats
    context['categorys'] = categorys
    context['authors'] = authors
    if request.method =="POST":
        name = request.POST.get('name')
        short_details= request.POST.get('short_details')
        description= request.POST.get('description')
        author_id= request.POST.get('author')
        author_instance = Author.objects.get(id=author_id)
        
        category_id= request.POST.get('category')
        category_instance = Category.objects.get(id=category_id)
        
        date= request.POST.get('date')
        book_code= request.POST.get('book_code')
        price= request.POST.get('price')
        discount_price= request.POST.get('discount_price')
        stock = request.POST.get('stock')
        image = request.FILES.get('image')
        
        format_id = request.POST.get('format')
        format_instance = Format.objects.get(id=format_id)
        page = request.POST.get('page')
        language = request.POST.get('language')

        book = Book(name=name, short_details=short_details, description=description, author=author_instance, category=category_instance, publication_data=date, book_code = book_code, price=price, discount_price=discount_price,stock=stock, image=image, format=format_instance, page=page, language=language)
        book.save()
        messages.success(request, "Add Successfully")
        return redirect('dashboard:all_books')
    return render(request, 'html/dashboard/add_book.html', context)



def book_category_page(request):
    context ={}
    category = Category.objects.all()
    context['categorys'] = category
    return render(request, "html/dashboard/books_category.html", context)

def product_by_category(request,id):
    context ={}
    category = get_object_or_404(Category,id=id)
    book = Book.objects.filter(category=category)
    context['categorys'] = category
    context['books'] = book
    return render(request, "html/dashboard/product_by_category.html", context)

def product_by_author(request,id):
    context ={}
    author = get_object_or_404(Author,id=id)
    book = Book.objects.filter(author=author, stock__gt=0)
    context['books'] = book
    context['author'] = author
    return render(request, "html/dashboard/product_by_category.html", context)

def edit_category(request, id):
    edit_category = get_object_or_404(Category,id=id)
    if request.method == "POST":
        edit_category.name = request.POST.get('name')
        edit_category.save()
        messages.success(request,"Updated Successfully")
        return redirect('dashboard:book_category_page')
    context={}
    context['edit_category'] = edit_category
    return render(request, 'html/dashboard/edit_category.html', context)

def book_category_delete(request, id):
     delete_category = get_object_or_404(Category,id=id)
     delete_category.delete()
     messages.success(request, "Banner Delete Successfully")
     return redirect('dashboard:book_category_page')

def add_book_category(request):
    if request.method == "POST":
        name = request.POST.get('name')
        category = Category(name=name)
        category.save()
        messages.success(request, "Category Add Successfully")
        return redirect('dashboard:book_category_page')
    return render(request, "html/dashboard/add_book_category.html")

def author(request):
    context ={}
    author = Author.objects.all()
    context["authors"] = author
    return render(request, 'html/dashboard/author.html', context)
def author_edit(request, id):
    edit = get_object_or_404(Author, id=id)
    if request.method == "POST":
        edit.name = request.POST.get('name')
        edit.description = request.POST.get('description')
        if request.FILES.get('image'):
            edit.image = request.FILES.get('image')
        edit.save()
        messages.success(request, "Update Successfully")
        return redirect('dashboard:author')
    context={}
    context['author'] = edit
    return render(request, 'html/dashboard/author_edit.html', context)
def author_delete(request,id):
    delete = get_object_or_404(Author, id=id)
    delete.delete()
    messages.success(request, "Banner Delete Successfully")
    return redirect('dashboard:author')
def author_add(request):
    if request.method == "POST":
        name = request.POST.get('name')
        description = request.POST.get('description')
        image = request.FILES.get('image')
        author = Author(name=name, description=description, image=image)
        author.save()
        messages.success(request, "Add Successfully")
        return redirect('dashboard:author')
    return render(request, "html/dashboard/author_add.html")

templates/html/dashboard/admin.html
{% load static %}
{% include 'html/components/dashboard_nav.html' %}
<div class="grid columns-12 gap-6">
    <div class="g-col-12 mt-6">
        <div class=" my-5 p-5 bg-light rounded">
            <div class="row align-items-center">
              
                <div class="col-md-3">
                    <h1 class="lead mb-0" style="font-size: 24px; color:#1c3faa; font-weight: 400;">BANNER SECTION</h1>

                </div>
            
                <div class="col-md-4 d-flex ">
                    <a href="{% url 'dashboard:add_banner' %}">
                        <button type="button" class="btn btn-primary btn-lg">ADD BANNER</button>
                    </a>
                </div>

                <div class="col-md-3 d-flex justify-content-end">
                    <a href="{% url 'dashboard:on_sale_banner' sale_offers.id %}">
                        <button type="button" class="btn btn-primary btn-lg">EDIT ON SALE OFFER</button>
                    </a>
                </div>

                <div class="col-md-2 d-flex justify-content-end">
                    <a href="{% url 'dashboard:edit_offer_banner' on_offers.id %}">
                        <button type="button" class="btn btn-primary btn-lg">EDIT OFFER</button>
                    </a>
                </div>

                
            </div>
        </div>
        <div class="intro-y overflow-auto overflow-lg-visible mt-10 mt-sm-0">
            <table class="table table-report mt-sm-2">
                <thead>
                    <tr>
                        <th class="text-nowrap"></th>

                        <th class="text-nowrap">IMAGES</th>
                        <th class="text-nowrap">TITLE</th>
                        <th class="text-center text-nowrap">DESCRIPTION</th>
                        <th class="text-center text-nowrap">STATUS</th>
                        <th class="text-center text-nowrap">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    {% for banner in banners %}
                    
                    <tr class="intro-x">
                        <td class="text-center">{{ forloop.counter }}</td>
                        <td class="w-40">
                            <div class="d-flex">
                                <div class="w-10 h-10 image-fit zoom-in">
                                    <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="{{ banner.image.url }}" title="Uploaded at 16 July 2021">
                                </div>
                            </div>
                        </td>
                        <td>
                            <a href="index.html" class="fw-medium text-nowrap">{{ banner.title }}</a> 
                            
                        </td>
                        <td class="text-center">{{ banner.description|striptags|truncatewords:10 }}</td>
                        
                        {% if banner.is_active %}
                        
                        <td class="w-40">
                            <div class="d-flex align-items-center justify-content-center text-theme-9"> <i data-feather="check-square" class="w-4 h-4 me-2"></i> Active </div>
                        </td>
                        {% else %}

                        <td class="w-40">
                            <div class="d-flex align-items-center justify-content-center text-theme-6"> <i data-feather="check-square" class="w-4 h-4 me-2"></i> Inactive </div>
                        </td>
                        {% endif %}
                        <td class="table-report__action w-56">
                            <div class="d-flex justify-content-center align-items-center">
                                <a class="d-flex align-items-center me-3" href="{% url 'dashboard:editdata' banner.id  %}"> <i data-feather="check-square" class="w-4 h-4 me-1"></i> Edit </a>
                                <a class="d-flex align-items-center text-theme-6" href="{% url 'dashboard:banner_delete' banner.id %}"> <i data-feather="trash-2" class="w-4 h-4 me-1"></i> Delete </a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    


         
                </tbody>
            </table>
        </div>
        
    </div>
    <!-- END: Weekly Top Products -->
</div>
</div>

</div>

{% include 'html/components/dashboard_footer.html' %}


<!-- <tr class="intro-x">
    <td class="w-40">
        <div class="d-flex">
            <div class="w-10 h-10 image-fit zoom-in">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-2.jpg" title="Uploaded at 15 January 2021">
            </div>
            <div class="w-10 h-10 image-fit zoom-in ms-n5">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-5.jpg" title="Uploaded at 16 January 2021">
            </div>
            <div class="w-10 h-10 image-fit zoom-in ms-n5">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-9.jpg" title="Uploaded at 22 July 2021">
            </div>
        </div>
    </td>
    <td>
        <a href="index.html" class="fw-medium text-nowrap">Dell XPS 13</a> 
        <div class="text-gray-600 fs-xs text-nowrap mt-0.5">PC &amp; Laptop</div>
    </td>
    <td class="text-center">66</td>
    <td class="w-40">
        <div class="d-flex align-items-center justify-content-center text-theme-6"> <i data-feather="check-square" class="w-4 h-4 me-2"></i> Inactive </div>
    </td>
    <td class="table-report__action w-56">
        <div class="d-flex justify-content-center align-items-center">
            <a class="d-flex align-items-center me-3" href="index.html"> <i data-feather="check-square" class="w-4 h-4 me-1"></i> Edit </a>
            <a class="d-flex align-items-center text-theme-6" href="index.html"> <i data-feather="trash-2" class="w-4 h-4 me-1"></i> Delete </a>
        </div>
    </td>
</tr>
<tr class="intro-x">
    <td class="w-40">
        <div class="d-flex">
            <div class="w-10 h-10 image-fit zoom-in">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-13.jpg" title="Uploaded at 7 July 2022">
            </div>
            <div class="w-10 h-10 image-fit zoom-in ms-n5">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-6.jpg" title="Uploaded at 7 December 2021">
            </div>
            <div class="w-10 h-10 image-fit zoom-in ms-n5">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-1.jpg" title="Uploaded at 13 February 2021">
            </div>
        </div>
    </td>
    <td>
        <a href="index.html" class="fw-medium text-nowrap">Nikon Z6</a> 
        <div class="text-gray-600 fs-xs text-nowrap mt-0.5">Photography</div>
    </td>
    <td class="text-center">95</td>
    <td class="w-40">
        <div class="d-flex align-items-center justify-content-center text-theme-6"> <i data-feather="check-square" class="w-4 h-4 me-2"></i> Inactive </div>
    </td>
    <td class="table-report__action w-56">
        <div class="d-flex justify-content-center align-items-center">
            <a class="d-flex align-items-center me-3" href="index.html"> <i data-feather="check-square" class="w-4 h-4 me-1"></i> Edit </a>
            <a class="d-flex align-items-center text-theme-6" href="index.html"> <i data-feather="trash-2" class="w-4 h-4 me-1"></i> Delete </a>
        </div>
    </td>
</tr>
<tr class="intro-x">
    <td class="w-40">
        <div class="d-flex">
            <div class="w-10 h-10 image-fit zoom-in">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-3.jpg" title="Uploaded at 19 September 2020">
            </div>
            <div class="w-10 h-10 image-fit zoom-in ms-n5">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-3.jpg" title="Uploaded at 21 May 2021">
            </div>
            <div class="w-10 h-10 image-fit zoom-in ms-n5">
                <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="dist/images/preview-1.jpg" title="Uploaded at 30 December 2021">
            </div>
        </div>
    </td>
    <td>
        <a href="index.html" class="fw-medium text-nowrap">Nikon Z6</a> 
        <div class="text-gray-600 fs-xs text-nowrap mt-0.5">Photography</div>
    </td>
    <td class="text-center">176</td>
    <td class="w-40">
        <div class="d-flex align-items-center justify-content-center text-theme-9"> <i data-feather="check-square" class="w-4 h-4 me-2"></i> Active </div>
    </td>
    <td class="table-report__action w-56">
        <div class="d-flex justify-content-center align-items-center">
            <a class="d-flex align-items-center me-3" href="index.html"> <i data-feather="check-square" class="w-4 h-4 me-1"></i> Edit </a>
            <a class="d-flex align-items-center text-theme-6" href="index.html"> <i data-feather="trash-2" class="w-4 h-4 me-1"></i> Delete </a>
        </div>
    </td>
</tr> -->

templates/html/dashboard/author.html
{% include 'html/components/dashboard_nav.html' %}


<div class="grid columns-12 gap-6">
    <div class="g-col-12 mt-6">
        <div class=" my-5 p-5 bg-light rounded">
            <div class="row align-items-center">
              
                <div class="col-md-8">
                    <h1 class="lead mb-0" style="font-size: 24px; color:#1c3faa; font-weight: 400;">SHOW ALL AUTHOR</h1>
                </div>
                <div class="col-md-4 d-flex justify-content-end">
                    <a href="{% url 'dashboard:author_add' %}">
                        <button type="button" class="btn btn-primary btn-lg">ADD AUTHOR</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="intro-y overflow-auto overflow-lg-visible mt-10 mt-sm-0">
            <table class="table table-report mt-sm-2">
                <thead>
                    <tr>
                        <th class="text-nowrap"></th>

                        <th class="text-nowrap">IMAGE</th>
                        <th class="text-center text-nowrap">NAME</th>
                        <th class="text-center text-nowrap">TOTAL BOOKS</th>
                        <th class="text-center text-nowrap">SHOW BOOKS</th>
                        <th class="text-center text-nowrap">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    {% for author in authors %}
                    <tr class="intro-x">
                        <td class="text-center">{{ forloop.counter }}</td>
                     
                        <td class="w-40">
                            <div class="d-flex">
                                <div class="w-10 h-10 image-fit zoom-in">
                                    <img alt="Rubick Bootstrap HTML Admin Template" class="tooltip rounded-circle" src="{{ author.image.url }}" title="{{ author.name }}">
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="d-flex align-items-center justify-content-center">
                                <a href="index.html" class="fw-medium text-nowrap">
                                    <p>{{ author.name }}</p>
                                </a>
                            </div>
                           
                            
                        </td>

                        <td class="w-45">
                            <div class="d-flex align-items-center justify-content-center text-theme-6"> {{ author.book_set.count }} </div>
                        </td>
                        <td class="w-45">
                            <a href="{% url 'dashboard:product_by_author' author.id %}">
                                <div class="d-flex align-items-center justify-content-center text-theme-9"> <i data-feather="eye" class="w-4 h-4 me-2"></i> Show </div>
                            </a>
                        </td>
                       
                        <td class="table-report__action w-56">
                            <div class="d-flex justify-content-center align-items-center">
                                <a class="d-flex align-items-center me-3" href="{% url 'dashboard:author_edit' author.id %}"> <i data-feather="check-square" class="w-4 h-4 me-1"></i> Edit </a>

                                <div class="delete-form">
                                    <a class="delete-btn d-flex align-items-center text-theme-6" href="{% url 'dashboard:author_delete' author.id %}"> <i data-feather="trash-2" class="w-4 h-4 me-1"></i> Delete </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% empty %}
                        
                    {% endfor %}
                    

                </tbody>
            </table>
        </div>
        
    </div>
    <!-- END: Weekly Top Products -->
</div>

{% include 'html/components/dashboard_footer.html' %}

templates/html/dashboard/books_category.html
{% include 'html/components/dashboard_nav.html' %}


<div class="grid columns-12 gap-6">
    <div class="g-col-12 mt-6">
        <div class=" my-5 p-5 bg-light rounded">
            <div class="row align-items-center">
              
                <div class="col-md-8">
                    <h1 class="lead mb-0" style="font-size: 24px; color:#1c3faa; font-weight: 400;">SHOW ALL CATEGORY</h1>
                </div>
                <div class="col-md-4 d-flex justify-content-end">
                    <a href="{% url 'dashboard:add_book_category' %}">
                        <button type="button" class="btn btn-primary btn-lg">ADD CATEGORY</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="intro-y overflow-auto overflow-lg-visible mt-10 mt-sm-0">
            <table class="table table-report mt-sm-2">
                <thead>
                    <tr>
                        <th class="text-nowrap"></th>

                        <th class="text-nowrap">CATEGORY</th>
                        <th class="text-center text-nowrap">TOTAL BOOKS</th>
                        <th class="text-center text-nowrap">SHOW BOOKS</th>
                        <th class="text-center text-nowrap">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categorys %}
                    <tr class="intro-x">
                        <td class="text-center">{{ forloop.counter }}</td>
                      
                        <td>
                            <a href="index.html" class="fw-medium text-nowrap">
                                <p>{{ category.name }}</p>
                            </a> 
                            
                        </td>

                        <td class="w-45">
                            <div class="d-flex align-items-center justify-content-center text-theme-6"> {{ category.book_set.count }} </div>
                        </td>
                        <td class="w-45">
                            <a href="{% url 'dashboard:product_by_category' category.id %}">
                                <div class="d-flex align-items-center justify-content-center text-theme-9"> <i data-feather="eye" class="w-4 h-4 me-2"></i> Show </div>
                            </a>
                        </td>
                       
                        <td class="table-report__action w-56">
                            <div class="d-flex justify-content-center align-items-center">
                                <a class="d-flex align-items-center me-3" href="{% url 'dashboard:edit_category' category.id %}"> <i data-feather="check-square" class="w-4 h-4 me-1"></i> Edit </a>

                                <div class="delete-form">
                                    <a class="delete-btn d-flex align-items-center text-theme-6" href="{% url 'dashboard:category_delete' category.id %}"> <i data-feather="trash-2" class="w-4 h-4 me-1"></i> Delete </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% empty %}
                        
                    {% endfor %}
                    

                </tbody>
            </table>
        </div>
        
    </div>
    <!-- END: Weekly Top Products -->
</div>

{% include 'html/components/dashboard_footer.html' %}

templates/html/dashboard/on_sale.html
{% load static %}
{% include 'html/components/dashboard_nav.html' %}

<div class="content">

<div class="intro-y d-flex flex-column flex-sm-row align-items-center pt-8 pb-8">
<h1 class="fs-lg fw-medium me-auto">Edit Offer Banner</h1>
</div>

<!-- BEGIN: Post Content -->


<form action="{% url 'dashboard:on_sale_banner' on_offer.id %}" method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col">
        <h2 class="mb-2 fs-lg  me-auto">Edit Title</h2>
        <input name="title" type="text" class="intro-y form-control py-3 px-4 box border-white dark-border-dark-3 pe-10 placeholder-theme-13" value="{{ on_offer.title }}">
      </div>
      <div class="col">
        <h2 class="mb-2 fs-lg  me-auto">Enter discount %</h2>
        <input name="discount" type="number" class="intro-y form-control py-3 px-4 box border-white dark-border-dark-3 pe-10 placeholder-theme-13" value="{{ on_offer.discount }}">
      </div>
    </div>
    <div class="w-full w-sm-auto d-flex pt-6 mt-sm-0 d-flex">
        <a href="{% url 'dashboard:CustomAdmin' %}"><button type="button" class="btn box text-gray-700 dark-text-gray-300 me-2 d-flex ms-auto ms-sm-0"> Cencel </button></a>
        <button type="submit" class="dropdown-toggle btn btn-primary shadow-md d-flex" aria-expanded="false"> Save </button>
    </div>
  </form>

</div>


{% include 'html/components/dashboard_footer.html' %}