Books/urls.py
from django.urls import path
from Books.views import *

urlpatterns = [
   
    
]

Dashboard/urls.py
from django.urls import path
from Dashboard.views import *

app_name = "dashboard"

urlpatterns = [
    path('', CustomAdmin, name="CustomAdmin"),
    path('table/', custom_table, name="custom_table"),
    path('banner_section/',banner_section, name='banner_section'),
    path('banner_section/add_banner/', add_banner, name="add_banner"),
    path('banner_section/editdata/<int:id>/', editdata, name='editdata'),
    path('banner_delete/<int:id>/', banner_delete, name='banner_delete'),
    path('banner_section/on_sale/<int:id>/', on_sale_banner, name="on_sale_banner"),
    path('banner_section/edit_offer/<int:id>/', edit_offer_banner, name="edit_offer_banner"),
    path('books_category/', book_category_page, name="book_category_page"),
    path('book_category/edit/<int:id>/', edit_category, name="edit_category"),
    path('book_category/edit_category_delete/<int:id>/', book_category_delete, name="category_delete"),
    path('book_category/add_category/', add_book_category, name="add_book_category"),
    path('book_category/book_filter_category/<int:id>', product_by_category, name="product_by_category"),
    path('book_category/book_filter_author/<int:id>', product_by_author, name="product_by_author"),
    path('books/', all_books, name="all_books"),
    path('books/add_book/', add_book, name="add_book"),
    path('author/', author, name="author"),
    path('author/author_edit/<int:id>', author_edit, name="author_edit"),
    path('author/author_delete/<int:id>', author_delete, name="author_delete"),
    path('author/author_add/', author_add, name="author_add"),
    
    
]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from .views import admin_page
from django.conf import settings
from django.conf.urls.static import static
# from e_commerce import Dashboard


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('IndexPage.urls')),
    path('dashboard/',admin_page, name='admin_page'),
    path('dashboard/', include(('Dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('book/', include('Books.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/html/components/dashboard_nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="light">
<!-- BEGIN: Head -->
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Rubick admin is super flexible, powerful, clean & modern responsive bootstrap admin template with unlimited possibilities.">
<meta name="keywords" content="admin template, Rubick Admin Template, dashboard template, flat admin template, responsive admin template, web app">
<meta name="author" content="LEFT4CODE">
<title>Dashboard - Rubick - Bootstrap HTML Admin Template</title>
<!-- BEGIN: CSS Assets-->
<link rel="stylesheet" href="{% static 'dashboard/css/app.css' %}"/>
<link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}"/>
<!-- END: CSS Assets-->
</head>
<!-- END: Head --
    <body class="main">
        <!-- BEGIN: Mobile Menu -->
        
        <!-- END: Mobile Menu -->
        <div class="d-flex">
            <!-- BEGIN: Side Menu -->
            <nav class="side-nav">
                <a href="{% url 'dashboard:CustomAdmin' %}" class="intro-x d-flex align-items-center ps-5 pt-4">
                    <img alt="Rubick Tailwind HTML Admin Template" class="w-6" src="{% static 'dashboard/images/logo.svg' %}">
                    <span class="d-none d-xl-block text-white fs-lg ms-3"> Ru<span class="fw-medium">bick</span> </span>
                </a>
                <div class="side-nav__devider my-6"></div>
                <ul>
                    
                   
                    <li>
                        <a href="{% url 'dashboard:banner_section' %}" class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="tool"></i> </div>
                            <div class="side-menu__title"> BANNER </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:all_books' %}" class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="book"></i> </div>
                            <div class="side-menu__title"> BOOKS</div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:book_category_page' %}" class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="briefcase"></i> </div>
                            <div class="side-menu__title"> BOOKS CATEGORY</div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:author' %}" class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="award"></i> </div>
                            <div class="side-menu__title"> AUTHOR </div>
                        </a>
                    </li>
                    <li>
                        <a href="side-menu-light-file-manager.html" class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="hard-drive"></i> </div>
                            <div class="side-menu__title"> File Manager </div>
                        </a>
                    </li>
                   
                </ul>
            </nav>
            <!-- END: Side Menu -->
            <!-- BEGIN: Content -->
            <div class="content">
                <!-- BEGIN: Top Bar -->
                <div class="top-bar">
                    <!-- BEGIN: Breadcrumb -->
                    <div class="-intro-x breadcrumb me-auto d-none d-sm-flex"> <a href="{% url 'dashboard:CustomAdmin' %}">Application</a> <i data-feather="chevron-right" class="breadcrumb__icon"></i> <a href="index.html" class="breadcrumb--active">{{ banner }}</a> </div>
                    <!-- END: Breadcrumb -->
                    <!-- BEGIN: Search -->
                    <div class="intro-x position-relative me-3 me-sm-6">
                        <div class="search d-none d-sm-block">
                            <input type="text" class="search__input form-control border-transparent" placeholder="Search...">
                            <i data-feather="search" class="search__icon dark-text-gray-300"></i> 
                        </div>
                        <a class="notification d-sm-none" href="index.html"> <i data-feather="search" class="notification__icon dark-text-gray-300"></i> </a>
                        <div class="search-result">
                            <div class="search-result__content">
                                <div class="search-result__content__title">Pages</div>
                                <div class="mb-5">
                                    <a href="index.html" class="d-flex align-items-center">
                                        <div class="w-8 h-8 bg-theme-18 text-theme-9 d-flex align-items-center justify-content-center rounded-circle"> <i class="w-4 h-4" data-feather="inbox"></i> </div>
                                        <div class="ms-3">Mail Settings</div>
                                    </a>
                                    <a href="index.html" class="d-flex align-items-center mt-2">
                                        <div class="w-8 h-8 bg-theme-17 text-theme-11 d-flex align-items-center justify-content-center rounded-circle"> <i class="w-4 h-4" data-feather="users"></i> </div>
                                        <div class="ms-3">Users & Permissions</div>
                                    </a>
                                    <a href="index.html" class="d-flex align-items-center mt-2">
                                        <div class="w-8 h-8 bg-theme-14 text-theme-10 d-flex align-items-center justify-content-center rounded-circle"> <i class="w-4 h-4" data-feather="credit-card"></i> </div>
                                        <div class="ms-3">Transactions Report</div>
                                    </a>
                                </div>
                                <div class="search-result__content__title">Users</div>
                                <div class="mb-5">
                                    <a href="index.html" class="d-flex align-items-center mt-2">
                                        <div class="w-8 h-8 image-fit">
                                            <img alt="Rubick Tailwind HTML Admin Template" class="rounded-circle" src="dist/images/profile-14.jpg">
                                        </div>
                                        <div class="ms-3">{{ user.username }}</div>
                                        <div class="ms-auto w-48 truncate text-gray-600 fs-xs text-end">robertdeniro@left4code.com</div>
                                    </a>
                                    <a href="index.html" class="d-flex align-items-center mt-2">
                                        <div class="w-8 h-8 image-fit">
                                            <img alt="Rubick Tailwind HTML Admin Template" class="rounded-circle" src="dist/images/profile-3.jpg">
                                        </div>
                                        <div class="ms-3">Angelina Jolie</div>
                                        <div class="ms-auto w-48 truncate text-gray-600 fs-xs text-end">angelinajolie@left4code.com</div>
                                    </a>
                                    <a href="index.html" class="d-flex align-items-center mt-2">
                                        <div class="w-8 h-8 image-fit">
                                            <img alt="Rubick Tailwind HTML Admin Template" class="rounded-circle" src="dist/images/profile-5.jpg">
                                        </div>
                                        <div class="ms-3">{{ user.username }}</div>
                                        <div class="ms-auto w-48 truncate text-gray-600 fs-xs text-end">robertdeniro@left4code.com</div>
                                    </a>
                                    <a href="index.html" class="d-flex align-items-center mt-2">
                                        <div class="w-8 h-8 image-fit">
                                            <img alt="Rubick Tailwind HTML Admin Template" class="rounded-circle" src="dist/images/profile-1.jpg">
                                        </div>
                                        <div class="ms-3">Bruce Willis</div>
                                        <div class="ms-auto w-48 truncate text-gray-600 fs-xs text-end">brucewillis@left4code.com</div>
                                    </a>
                                </div>
                                <div class="search-result__content__title">Products</div>
                                <a href="index.html" class="d-flex align-items-center mt-2">
                                    <div class="w-8 h-8 image-fit">
                                        <img alt="Rubick Tailwind HTML Admin Template" class="rounded-circle" src="dist/images/preview-4.jpg">
                                    </div>
                                    <div class="ms-3">Sony Master Series A9G</div>
                                    <div class="ms-auto w-48 truncate text-gray-600 fs-xs text-end">Electronic</div>
                                </a>
                                <a href="index.html" class="d-flex align-items-center mt-2">
                                    <div class="w-8 h-8 image-fit">
                                        <img alt="Rubick Tailwind HTML Admin Template" class="rounded-circle" src="dist/images/preview-1.jpg">
                                    </div>
                                    <div class="ms-3">Samsung Q90 QLED TV</div>
                                    <div class="ms-auto w-48 truncate text-gray-600 fs-xs text-end">Electronic</div>
                                </a>
                                <a href="index.html" class="d-flex align-items-center mt-2">
                                    <div class="w-8 h-8 image-fit">
                                        <img alt="Rubick Tailwind HTML Admin Template" class="rounded-circle" src="dist/images/preview-11.jpg">
                                    </div>
                                    <div class="ms-3">Samsung Q90 QLED TV</div>
                                    <div class="ms-auto w-48 truncate text-gray-600 fs-xs text-end">Electronic</div>
                                </a>
                                <a href="index.html" class="d-flex align-items-center mt-2">
                                    <div class="w-8 h-8 image-fit">
                                        <img alt="Rubick Tailwind HTML Admin Template" class="rounded-circle" src="dist/images/preview-5.jpg">
                                    </div>
                                    <div class="ms-3">Nike Tanjun</div>
                                    <div class="ms-auto w-48 truncate text-gray-600 fs-xs text-end">Sport &amp; Outdoor</div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="intro-x dropdown w-8 h-8">
                        <div class="dropdown-toggle w-8 h-8 rounded-pill overflow-hidden shadow-lg image-fit zoom-in" role="button" aria-expanded="false" data-bs-toggle="dropdown">
                            <img alt="Rubick Tailwind HTML Admin Template" src="dist/images/profile-2.jpg">
                        </div>
                        <div class="dropdown-menu w-56">
                            <ul class="dropdown-content bg-theme-26 dark-bg-dark-6 text-white">
                                <li class="p-2">
                                    <div class="fw-medium text-white">{{ user.username }}</div>
                                    <div class="fs-xs text-theme-28 mt-0.5 dark-text-gray-600">DevOps Engineer</div>
                                </li>
                                <li>
                                    <hr class="dropdown-divider border-theme-27 dark-border-dark-3">
                                </li>
                                <li>
                                    <a href="index.html" class="dropdown-item text-white bg-theme-1-hover dark-bg-dark-3-hover"> <i data-feather="user" class="w-4 h-4 me-2"></i> Profile </a>
                                </li>
                                <li>
                                    <a href="index.html" class="dropdown-item text-white bg-theme-1-hover dark-bg-dark-3-hover"> <i data-feather="edit" class="w-4 h-4 me-2"></i> Add Account </a>
                                </li>
                                <li>
                                    <a href="index.html" class="dropdown-item text-white bg-theme-1-hover dark-bg-dark-3-hover"> <i data-feather="lock" class="w-4 h-4 me-2"></i> Reset Password </a>
                                </li>
                                <li>
                                    <a href="index.html" class="dropdown-item text-white bg-theme-1-hover dark-bg-dark-3-hover"> <i data-feather="help-circle" class="w-4 h-4 me-2"></i> Help </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider border-theme-27 dark-border-dark-3">
                                </li>
                                <li>
                                    <a href="index.html" class="dropdown-item text-white bg-theme-1-hover dark-bg-dark-3-hover"> <i data-feather="toggle-right" class="w-4 h-4 me-2"></i> Logout </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- END: Account Menu -->
                </div>
                <!-- END: Top Bar -->
                
       